//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long ID { get; set; }
        public int Patient_Questionnaires_ID { get; set; }
        public long Questionnaire_Question_ID { get; set; }
        public Nullable<long> Choice_ID { get; set; }
        public string TextAnswer { get; set; }
        public Nullable<short> Processed { get; set; }
        public Nullable<long> DB_ID { get; set; }
        public Nullable<int> DB_CID { get; set; }
        public Nullable<long> Question_Choice_ID { get; set; }
        public Nullable<int> SenderDBID { get; set; }
        public int Revision { get; set; }
        public int SyncError { get; set; }
        public string ModifiedByUser { get; set; }
        public System.DateTime ModifiedDatetime { get; set; }
        public Nullable<int> Question_SubQuestionRowHeader_ID { get; set; }
    
        public virtual Choice Choice { get; set; }
        public virtual Patient_Questionnaire Patient_Questionnaires { get; set; }
        public virtual Question_Choice Question_Choice { get; set; }
        public virtual Questionnaire_Question Questionnaire_Question { get; set; }
        public virtual Question_SubQuestionRowHeader Question_SubQuestionRowHeader { get; set; }
    }
}
