//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ButtonModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ButtonModel()
        {
            this.ControlModels = new HashSet<ControlModel>();
            this.PumpSpeedChanges = new HashSet<PumpSpeedChange>();
            this.PumpSpeedLevels = new HashSet<PumpSpeedLevel>();
        }
    
        public int Id { get; set; }
        public ControlPanelControlType ControlType { get; set; }
        public int ControlPanelModel_Id { get; set; }
        public ControlAction ActionIdentifier { get; set; }
        public bool IsEnabled { get; set; }
        public int ActionRepeatCount { get; set; }
        public string Label { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public bool AllowRepeat { get; set; }
        public bool AllowDropDown { get; set; }
        public bool AutoGoToNext { get; set; }
        public PresetControl BaseControlPreset { get; set; }
        public EditableButtonModelProperties EditableButtonModelProperties { get; set; }
        public FunctionKey FunctionKey { get; set; }
    
        public virtual ControlPanelModel ControlPanelModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlModel> ControlModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PumpSpeedChange> PumpSpeedChanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PumpSpeedLevel> PumpSpeedLevels { get; set; }
    }
}
