//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelMapping
    {
        public int Id { get; set; }
        public string HardwareDeviceId { get; set; }
        public Nullable<int> HardwareChannelId { get; set; }
        public Nullable<int> HardwareServiceId { get; set; }
        public int ChannelModelId { get; set; }
    
        public virtual ChannelModel ChannelModel { get; set; }
    }
}
