//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChannelModel()
        {
            this.ChannelMappings = new HashSet<ChannelMapping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProtocolModel_Id { get; set; }
        public DataQuantityUnit DataQuantityUnit { get; set; }
        public DataQuantityType DataQuantityType { get; set; }
        public int ScaleMin { get; set; }
        public int ScaleMax { get; set; }
        private string LineColorInternal { get; set; }
        public int ChannelIndex { get; set; }
        public ChannelType ChannelType { get; set; }
        public string DependentChannelIndexesString { get; set; }
        public int MasterZeroChannelIndex { get; set; }
        public string CalculationString { get; set; }
        public ChannelCalculationType ChannelCalculationType { get; set; }
        public int ChannelPosition { get; set; }
        public ChartDownSamplerType ChartDownSampler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelMapping> ChannelMappings { get; set; }
        public virtual ProtocolModel ProtocolModel { get; set; }
    }
}
