//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelConsumableCategory
    {
        public int ID { get; set; }
        public int InvestigationType { get; set; }
        public int ChannelId { get; set; }
        public int CategoryId { get; set; }
        public short QualifyLevel { get; set; }
        public bool Exclusive { get; set; }
    }
}
