//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartChannelEvent : Event
    {
        public int ChannelDisplayType { get; set; }
        public int ChannelId { get; set; }
        public int ChannelIndex { get; set; }
    
        public virtual ChannelModel ChannelModel { get; set; }
    }
}
