//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using Translations;

    public enum ChartDownSamplerType : int
    {
        [Display(ResourceType = typeof(Language), Name = nameof(Language.Enum_ChartDownSamplerType_None))]
        None = 0,
        [Display(ResourceType = typeof(Language), Name = nameof(Language.Enum_ChartDownSamplerType_Max))]
        Max = 1,
        [Display(ResourceType = typeof(Language), Name = nameof(Language.Enum_ChartDownSamplerType_MinMax))]
        MinMax = 2,
        [Display(ResourceType = typeof(Language), Name = nameof(Language.Enum_ChartDownSamplerType_Median))]
        Median = 3
    }
}
