//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consumable()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int BarcodeID { get; set; }
        public Nullable<long> Gtin { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Lot { get; set; }
        public string Serial { get; set; }
        public System.DateTime ScanDate { get; set; }
        public string CategoryName { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public Nullable<int> QualifyLevel { get; set; }
        public Nullable<int> QualifyLevelType { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public byte[] EncryptedBytes { get; set; }
        public byte[] TagId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
    }
}
