//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlModel
    {
        public int Id { get; set; }
        public ControlAction ActionIdentifier { get; set; }
        public bool IsEnabled { get; set; }
        public string Label { get; set; }
        public int ButtonModel_Id { get; set; }
        public int ControlModelIndex { get; set; }
        public string BackGroundColor { get; set; }
    
        public virtual ButtonModel ButtonModel { get; set; }
    }
}
