//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    
    public enum DeviceTypes : short
    {
        PM2 = 1,
        PL2 = 2,
        RO2 = 3,
        UC6 = 4,
        RC1600 = 5,
        RO2Simulator = 6,
        UC6Simulator = 7,
        US2Simulator = 8,
        US2 = 9,
        PM2Simulator = 10,
        PL2Simulator = 11,
        BTD = 12,
        MMSRCBPE17 = 13,
        FileSimulator = 14,
        BT2 = 15
    }
}
