//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    
    public enum DeviceConnectionType : int
    {
        USB = 0,
        BLUETOOTH = 1,
        TCP = 2,
        SIMULATOR = 3,
        BLUETOOTHLE = 4
    }
}
