//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    
    public enum DeviceConnectionStatus : short
    {
        Unknown = 0,
        Connected = 1,
        Disconnected = 2,
        Failed = 3,
        Connecting = 4,
        USBError = 5,
        BluetoothError = 6,
        CommunicationError = 7,
        Disconnecting = 8
    }
}
