//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    
    public enum EmgFilterRate : int
    {
        Milliseconds0 = 0,
        Milliseconds10 = 10,
        Milliseconds20 = 20,
        Milliseconds50 = 50,
        Milliseconds100 = 100,
        Milliseconds800 = 800
    }
}
