//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eula
    {
        public int ID { get; set; }
        public System.DateTime ActionDateTime { get; set; }
        public byte NumberOfSkipped { get; set; }
        public Laborie.Synergy.DataModel.EulaStates EulaState { get; set; }
    }
}
