//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsHistory
    {
        public long Id { get; set; }
        public long EventID { get; set; }
        public long BeginTime { get; set; }
        public long EndTime { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime DateTimeChanged { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
