//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Children = new HashSet<Event>();
            this.Results = new HashSet<Result>();
            this.ImageResults = new HashSet<ImageResult>();
            this.Media = new HashSet<Media>();
            this.EventsHistories = new HashSet<EventsHistory>();
        }
    
        public long ID { get; set; }
        public int test_id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Time { get; set; }
        public bool ShowInSummary { get; set; }
        public long BeginTime { get; set; }
        public long EndTime { get; set; }
        public Nullable<long> Parent_Id { get; set; }
        public EventType Event_Type { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Origin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Children { get; set; }
        public virtual Event Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageResult> ImageResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Media> Media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventsHistory> EventsHistories { get; set; }
    }
}
