//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrameDetail
    {
        public int Id { get; set; }
        public int MediaID { get; set; }
        public System.Guid GUID { get; set; }
        public long Index { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public decimal SampleTime { get; set; }
    
        public virtual Media Medium { get; set; }
    }
}
