//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedReport : WorkflowStepResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneratedReport()
        {
            this.GeneratedReportComponents = new HashSet<GeneratedReportComponent>();
        }
    
        public int Reports_ID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public bool Saved { get; set; }
        public string MRN { get; set; }
        public Nullable<System.DateTime> LastViewed { get; set; }
        public Nullable<bool> EMRSent { get; set; }
        public int MemberIDConfirmed { get; set; }
        public int MemberIDSubmittedToEMR { get; set; }
        public System.DateTime ModifiedDatetime { get; set; }
        public string ExportedFormat { get; set; }
    
        public virtual Report Report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneratedReportComponent> GeneratedReportComponents { get; set; }
    }
}
