//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedReportComponent
    {
        public long ID { get; set; }
        public int GeneratedReports_ID { get; set; }
        public Nullable<int> ReportComponents_ID { get; set; }
        public bool Include { get; set; }
        public int WorkflowStepResultId { get; set; }
    
        public virtual WorkflowStepResult WorkflowStepResult { get; set; }
    }
}
