//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    
    public enum ImageSubType : int
    {
        Unused = 0,
        SchaeferNomogram = 1,
        ICSNomogram = 2,
        LiverpoolAverageFlowRateNomogram = 3,
        LiverpoolMaximumFlowRateNomogram = 4,
        MiskolcAverageFlowRateNomogram = 5,
        MiskolcMaximumFlowRateNomogram = 6,
        SingleImage = 7,
        VideoFrame = 8
    }
}
