//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageResult()
        {
            this.ImageFrameResults = new HashSet<ImageFrameResult>();
        }
    
        public int Id { get; set; }
        public System.Guid UI { get; set; }
        public long Event_Id { get; set; }
        public byte[] ImageFile { get; set; }
        public ImageType ImageType { get; set; }
        public ImageSubType ImageSubType { get; set; }
        public string ImageTimestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageFrameResult> ImageFrameResults { get; set; }
    }
}
