//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Media()
        {
            this.FrameDetails = new HashSet<FrameDetail>();
        }
    
        public int Id { get; set; }
        public System.Guid ResourceGUID { get; set; }
        public string ResourceExtension { get; set; }
        public string ResourceFolder { get; set; }
        public int TestID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public long Event_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrameDetail> FrameDetails { get; set; }
        public virtual Event Event { get; set; }
    }
}
