//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Questionnaire : WorkflowStepResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient_Questionnaire()
        {
            this.Answers = new HashSet<Answer>();
            this.QuestionnaireScores = new HashSet<QuestionnaireScore>();
        }
    
        public System.DateTime DateAndTime { get; set; }
        public int Questionnaire_ID { get; set; }
        public Nullable<int> Test_ID { get; set; }
        public bool EmailSent { get; set; }
        public Nullable<int> EmailID { get; set; }
        public short Processed { get; set; }
        public int DB_CID { get; set; }
        public Nullable<long> DB_ID { get; set; }
        public Nullable<System.DateTime> DateAndTimeSubmitted { get; set; }
        public Nullable<System.DateTime> mod_datetime { get; set; }
        public Nullable<int> mod_by_id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SenderDBID { get; set; }
        public int Revision { get; set; }
        public int SyncError { get; set; }
        public string ModifiedByUser { get; set; }
        public System.DateTime ModifiedDatetime { get; set; }
        public int MemberIDValidated { get; set; }
        public Nullable<decimal> PercentComplete { get; set; }
        public Nullable<int> QuestionsPerPage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual SQuestionnaire SQuestionnaire { get; set; }
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireScore> QuestionnaireScores { get; set; }
    }
}
