//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhaseModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhaseModel()
        {
            this.ChallengeTemplateModels = new HashSet<ChallengeTemplateModel>();
            this.ChildPhases = new HashSet<PhaseModel>();
            this.StimulationSettingsModels = new HashSet<StimulationSettingsModel>();
            this.QCScores = new HashSet<QCScore>();
            this.PhaseEvents = new HashSet<PhaseEvent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        internal Nullable<int> CountdownTimerSecondsInternal { get; set; }
        public Nullable<PhaseIconType> IconType { get; set; }
        internal Nullable<int> DurationSecondsInternal { get; set; }
        internal Nullable<bool> AcquireDataInternal { get; set; }
        internal Nullable<int> RepeatCountInternal { get; set; }
        public Nullable<bool> TimerVisible { get; set; }
        internal string VisibleChannelsInternal { get; set; }
        public int PhaseOrder { get; set; }
        public Nullable<int> ParentPhaseId { get; set; }
        public Nullable<int> ControlPanelId { get; set; }
        internal string EventScopeInternal { get; set; }
        internal Nullable<int> AfterFlowTimeInternal { get; set; }
        public PhaseModelTypes PhaseType { get; set; }
        internal string ChannelValuesShownSeparatelyInternal { get; set; }
        public Nullable<int> PumpSpeed { get; set; }
        public Nullable<int> PullerSpeed { get; set; }
        public bool AutoCoughArtifactDetection { get; set; }
        public bool AutoProfileDetection { get; set; }
        public bool AutoTransmissionDetection { get; set; }
        public string AdditionalStatusBarItems { get; set; }
        public bool AutoBristolArtifactDetection { get; set; }
        public bool AutoFlowDetection { get; set; }
        public bool EnablePvrDialog { get; set; }
        public bool EnableAutomaticPostVoidedResidual { get; set; }
        public int QCTotalScore { get; set; }
        public int QCMaximumScore { get; set; }
        public bool AutoStartPhase { get; set; }
        public decimal SpecificGravity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChallengeTemplateModel> ChallengeTemplateModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhaseModel> ChildPhases { get; set; }
        public virtual PhaseModel ParentPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StimulationSettingsModel> StimulationSettingsModels { get; set; }
        public virtual ControlPanelModel ControlPanelModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCScore> QCScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhaseEvent> PhaseEvents { get; set; }
    }
}
