//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimaryReason
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrimaryReason()
        {
            this.PrimaryReasonsPhasesConfigurations = new HashSet<PrimaryReasonsPhasesConfiguration>();
            this.PrimaryReasonsQuestionnairesConfigurations = new HashSet<PrimaryReasonsQuestionnairesConfiguration>();
        }
    
        public int ID { get; set; }
        public int GroupingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryReasonsPhasesConfiguration> PrimaryReasonsPhasesConfigurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryReasonsQuestionnairesConfiguration> PrimaryReasonsQuestionnairesConfigurations { get; set; }
    }
}
