//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolModel : WorkflowStepConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProtocolModel()
        {
            this.ChannelModels = new HashSet<ChannelModel>();
            this.UsedServices = new HashSet<UsedService>();
        }
    
        public ChartScrollingMode Style { get; set; }
        public int WorkflowStepConfig_Id { get; set; }
        public double SampleRate { get; set; }
        public int RootPhaseId { get; set; }
        public bool EnableVideo { get; set; }
        public int VideoFrameRate { get; set; }
        public double FlowDelay { get; set; }
        public bool EnableGridLines { get; set; }
        public bool DisplayFullEMG { get; set; }
        public bool ChannelPanelRightAligned { get; set; }
        public EmgFilterRate EmgFilterRate { get; set; }
        public bool Monochrome { get; set; }
        public bool ClipEMG { get; set; }
        public bool UseQCProgressBar { get; set; }
        public decimal SpecificGravity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelModel> ChannelModels { get; set; }
        public virtual PhaseModel PhaseModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedService> UsedServices { get; set; }
    }
}
