//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PumpSpeedLevel
    {
        public int Id { get; set; }
        public int ButtonModel_Id { get; set; }
        public short Value { get; set; }
    
        public virtual ButtonModel ButtonModel { get; set; }
    }
}
