//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCScore
    {
        public int Id { get; set; }
        public int PhaseModelId { get; set; }
        public QCScoreType QCScoreTypeId { get; set; }
        public int QCScoreValue { get; set; }
        public bool IsScoreApplicable { get; set; }
    
        public virtual PhaseModel PhaseModel { get; set; }
    }
}
