//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityControlStepsWithPhase
    {
        public int ID { get; set; }
        public int PhaseID { get; set; }
        public int QualityControlStepID { get; set; }
    
        public virtual QualityControlStep QualityControlStep { get; set; }
    }
}
