//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireScore
    {
        public int ID { get; set; }
        public int PatientQnrID { get; set; }
        public int FormulaID { get; set; }
        public decimal Score { get; set; }
    
        public virtual Formula Formula { get; set; }
        public virtual Patient_Questionnaire Patient_Questionnaires { get; set; }
    }
}
