//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultNormalValue
    {
        public int Id { get; set; }
        public int ResultType { get; set; }
        public int RangeType { get; set; }
        public double MaxValue { get; set; }
        public double MinValue { get; set; }
        public int TargetGroup { get; set; }
        public int VisualRangeMax { get; set; }
        public int VisualRangeMin { get; set; }
        public string Notes { get; set; }
        public string ReferenceNumbers { get; set; }
    }
}
