//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewModel : WorkflowStepConfiguration
    {
        public Nullable<int> ControlPanelId { get; set; }
        public bool AutoExecute { get; set; }
    
        public virtual ControlPanelModel ControlPanelModel { get; set; }
    }
}
