//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SQuestion()
        {
            this.Question_Choice = new HashSet<Question_Choice>();
            this.Questionnaire_Question = new HashSet<Questionnaire_Question>();
            this.Question_SubQuestionRowHeader = new HashSet<Question_SubQuestionRowHeader>();
        }
    
        public int ID { get; set; }
        public string DisplayText { get; set; }
        public Nullable<int> SenderDBID { get; set; }
        public int Revision { get; set; }
        public Nullable<int> DB_ID { get; set; }
        public Nullable<int> DB_CID { get; set; }
        public int SyncError { get; set; }
        public string ModifiedByUser { get; set; }
        public System.DateTime ModifiedDatetime { get; set; }
        public byte ForGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_Choice> Question_Choice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questionnaire_Question> Questionnaire_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question_SubQuestionRowHeader> Question_SubQuestionRowHeader { get; set; }
    }
}
