//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StimulationSettingsModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int RampUpTimer { get; set; }
        public int StimulationTimer { get; set; }
        public int RampDownTimer { get; set; }
        public int FrequencyValue { get; set; }
        public int BandValue { get; set; }
        public int MaxCurrent { get; set; }
        public int ChannelNumberToDrawOn { get; set; }
        public int PhaseModel_Id { get; set; }
    }
}
