//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Study()
        {
            this.WorkflowStepResults = new HashSet<WorkflowStepResult>();
            this.StudyPrimaryReasons = new HashSet<StudyPrimaryReason>();
        }
    
        public int patient_id { get; set; }
        public int ID { get; set; }
        public int WorkflowConfigurationId { get; set; }
        public Nullable<short> LicenseId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public bool Mode { get; set; }
        public System.Guid UUID { get; set; }
        public string QualityControlStepTree { get; set; }
        public bool IsDirty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowStepResult> WorkflowStepResults { get; set; }
        public virtual WorkflowConfiguration WorkflowConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyPrimaryReason> StudyPrimaryReasons { get; set; }
        public virtual License License { get; set; }
    }
}
