//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test : WorkflowStepResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.Events = new HashSet<Event>();
            this.Patient_Questionnaires = new HashSet<Patient_Questionnaire>();
            this.Media = new HashSet<Media>();
            this.UDS_TestData = new HashSet<UDS_TestData>();
            this.Consumables = new HashSet<Consumable>();
            this.OffsetEvents = new HashSet<OffsetEvent>();
        }
    
        public Nullable<int> doctor_id { get; set; }
        public System.DateTime test_time { get; set; }
        public string test_name { get; set; }
        public string clinic_name { get; set; }
        public string test_type { get; set; }
        public string sched_machine { get; set; }
        public string test_machine { get; set; }
        public string cfg_file { get; set; }
        public string catheter_size { get; set; }
        public byte emg_type { get; set; }
        public bool upp_measured { get; set; }
        public bool emg_guard_reflex { get; set; }
        public string Hl7AppointmentId { get; set; }
        public Nullable<System.DateTime> Hl7AppointmentDatetime { get; set; }
        public string Hl7Comments { get; set; }
        public string Hl7EventType { get; set; }
        public byte TestStatus { get; set; }
        public byte reportSentStatus { get; set; }
        public string UDS_Test_Id { get; set; }
        public string XML_Content { get; set; }
        public byte SoftwareType { get; set; }
        public string SoftwareVersion { get; set; }
        public Nullable<short> Processed { get; set; }
        public int DB_CID { get; set; }
        public Nullable<int> DB_ID { get; set; }
        public byte[] diagnosis_ENC { get; set; }
        public byte[] comments_ENC { get; set; }
        public byte[] comments2_ENC { get; set; }
        public byte[] recommendations_ENC { get; set; }
        public byte[] Hl7Comments_ENC { get; set; }
        public byte[] dta_file_ENC { get; set; }
        public byte[] Xml_Content_ENC { get; set; }
        public Nullable<int> Ref_Test_Id { get; set; }
        public string Visit_Type { get; set; }
        public Nullable<int> Reffering_Doctor_id { get; set; }
        public string other_doctor_name { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<int> create_by_id { get; set; }
        public Nullable<System.DateTime> mod_datetime { get; set; }
        public Nullable<int> mod_by_id { get; set; }
        public Nullable<int> SenderDBID { get; set; }
        public int Revision { get; set; }
        public int SyncError { get; set; }
        public Nullable<int> dta_file_ENCRevision { get; set; }
        public Nullable<System.DateTime> dta_file_ENCDateTimeModified { get; set; }
        public Nullable<int> ScrollingRate { get; set; }
        public string ModifiedByUser { get; set; }
        public System.DateTime ModifiedDatetime { get; set; }
        public int dta_file_ENCSyncError { get; set; }
        public bool VisitDataSubmittedToEMR { get; set; }
        public string OriginalDirectoryToMoveFileTo { get; set; }
        public string ProtocolName { get; set; }
        public bool IsConsumableBypassed { get; set; }
        public int NewConsumableCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Questionnaire> Patient_Questionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Media> Media { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UDS_TestData> UDS_TestData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consumable> Consumables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffsetEvent> OffsetEvents { get; set; }
    }
}
