//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDS_TestData
    {
        public int Test_Id { get; set; }
        public int ChannelID { get; set; }
        public double DataRate { get; set; }
        public System.Guid ResourceGUID { get; set; }
        public ChannelDataType ChannelDataType { get; set; }
    }
}
