//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStepConfiguration
    {
        public int Id { get; set; }
        public int WorkflowConfig_Id { get; set; }
        public WorkflowStepType WorkflowStepType { get; set; }
        public string Name { get; set; }
        public bool ExecuteOnlyFromAnotherStep { get; set; }
        public int CompletionStatus { get; set; }
        public int WorkflowStepOrder { get; set; }
    
        public virtual WorkflowConfiguration WorkflowConfiguration { get; set; }
    }
}
