//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowConfiguration()
        {
            this.WorkflowStepConfigurations = new HashSet<WorkflowStepConfiguration>();
        }
    
        public int Id { get; set; }
        public WorkflowInvestigationType InvestigationType { get; set; }
        public string Name { get; set; }
        public bool IsPredefined { get; set; }
        public Nullable<bool> IsClinical { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowStepConfiguration> WorkflowStepConfigurations { get; set; }
    }
}
