//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laborie.Synergy.BarcodeTraceability.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laborie.Synergy.BarcodeTraceability.Translations.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Other Consumable.
        /// </summary>
        public static string Action_AddArbitraryConsumable {
            get {
                return ResourceManager.GetString("Action_AddArbitraryConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass.
        /// </summary>
        public static string Action_Bypass {
            get {
                return ResourceManager.GetString("Action_Bypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Action_Remove {
            get {
                return ResourceManager.GetString("Action_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumables Registration is Bypassed.
        /// </summary>
        public static string ConsumableBypass {
            get {
                return ResourceManager.GetString("ConsumableBypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable cannot be reuse.
        /// </summary>
        public static string Error_ConsumableCannotBeReuse {
            get {
                return ResourceManager.GetString("Error_ConsumableCannotBeReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Consumable is expired.
        /// </summary>
        public static string Error_ConsumableExpired {
            get {
                return ResourceManager.GetString("Error_ConsumableExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Consumable is registered to a different patient.
        /// </summary>
        public static string Error_ConsumableIsUsedByOtherPatientException {
            get {
                return ResourceManager.GetString("Error_ConsumableIsUsedByOtherPatientException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable barcode has already been used by the same patient more than 4 hours ago.
        /// </summary>
        public static string Error_ConsumableIsUsedBySamePatientAfterFourHoursException {
            get {
                return ResourceManager.GetString("Error_ConsumableIsUsedBySamePatientAfterFourHoursException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable time limit has expired.
        /// </summary>
        public static string Error_ConsumableTimeLimitExpiredException {
            get {
                return ResourceManager.GetString("Error_ConsumableTimeLimitExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate consumable already exists. Replace the duplicate consumable with a valid consumable type.
        /// </summary>
        public static string Error_ConsumableWithDuplicateBarcodeExistsException {
            get {
                return ResourceManager.GetString("Error_ConsumableWithDuplicateBarcodeExistsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A duplicate consumable already exists. Replace the duplicate consumable with a valid consumable type.
        /// </summary>
        public static string Error_ConsumableWithSameCategory {
            get {
                return ResourceManager.GetString("Error_ConsumableWithSameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GTIN registered to the connected consumable was not recognized.
        /// </summary>
        public static string Error_ConsumableWithUnknownCategory {
            get {
                return ResourceManager.GetString("Error_ConsumableWithUnknownCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connected consumable is not needed for the study.
        /// </summary>
        public static string Error_ConsumableWithUnwantedCategory {
            get {
                return ResourceManager.GetString("Error_ConsumableWithUnwantedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid or corrupt consumables has been scanned.
        /// </summary>
        public static string Error_InvalidConsumable {
            get {
                return ResourceManager.GetString("Error_InvalidConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expiry date .
        /// </summary>
        public static string Error_InvalidExpiryDate {
            get {
                return ResourceManager.GetString("Error_InvalidExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot or Serial number is larger than the acceptable limit.
        /// </summary>
        public static string Error_OverflowException {
            get {
                return ResourceManager.GetString("Error_OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable is Qualified, GTIN has to contain Laborie Code.
        /// </summary>
        public static string Error_QualifiedConsumableRequired {
            get {
                return ResourceManager.GetString("Error_QualifiedConsumableRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary consumable is not allowed..
        /// </summary>
        public static string Error_SecondaryNotAllowed {
            get {
                return ResourceManager.GetString("Error_SecondaryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Consumable Compatibility file is corrupt and does not match the File Signature. Please call Service. The Software will now close..
        /// </summary>
        public static string Invalid_ConsumableJSON_FileSignature {
            get {
                return ResourceManager.GetString("Invalid_ConsumableJSON_FileSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning Consumable.
        /// </summary>
        public static string IsScanningMessage {
            get {
                return ResourceManager.GetString("IsScanningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Label_Automatic {
            get {
                return ResourceManager.GetString("Label_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BladderVolume.
        /// </summary>
        public static string Label_BladderVolume {
            get {
                return ResourceManager.GetString("Label_BladderVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Consumables.
        /// </summary>
        public static string Label_CategoryName {
            get {
                return ResourceManager.GetString("Label_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumables.
        /// </summary>
        public static string Label_Consumables {
            get {
                return ResourceManager.GetString("Label_Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Consumable.
        /// </summary>
        public static string Label_ConsumableType {
            get {
                return ResourceManager.GetString("Label_ConsumableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_ConsumableTypeDescription {
            get {
                return ResourceManager.GetString("Label_ConsumableTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string Label_ConsumableTypeName {
            get {
                return ResourceManager.GetString("Label_ConsumableTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMG.
        /// </summary>
        public static string Label_Emg {
            get {
                return ResourceManager.GetString("Label_Emg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMG Abdominal.
        /// </summary>
        public static string Label_EmgAbd {
            get {
                return ResourceManager.GetString("Label_EmgAbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMG Pelvic.
        /// </summary>
        public static string Label_EmgPelvic {
            get {
                return ResourceManager.GetString("Label_EmgPelvic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMG Probe.
        /// </summary>
        public static string Label_EMGProbe {
            get {
                return ResourceManager.GetString("Label_EMGProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string Label_Expiry_Date {
            get {
                return ResourceManager.GetString("Label_Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string Label_Flow {
            get {
                return ResourceManager.GetString("Label_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTIN.
        /// </summary>
        public static string Label_GTIN {
            get {
                return ResourceManager.GetString("Label_GTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading Pump tubing, please hold tubing to Pump Enclosure..
        /// </summary>
        public static string Label_HoldPumpTubeError {
            get {
                return ResourceManager.GetString("Label_HoldPumpTubeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string Label_Identifier {
            get {
                return ResourceManager.GetString("Label_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfusedVolume.
        /// </summary>
        public static string Label_InfusedVolume {
            get {
                return ResourceManager.GetString("Label_InfusedVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number.
        /// </summary>
        public static string Label_Lot {
            get {
                return ResourceManager.GetString("Label_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manometry Probe.
        /// </summary>
        public static string Label_ManometryProbe {
            get {
                return ResourceManager.GetString("Label_ManometryProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manometry Tubing.
        /// </summary>
        public static string Label_ManometryTubing {
            get {
                return ResourceManager.GetString("Label_ManometryTubing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Label_Manual {
            get {
                return ResourceManager.GetString("Label_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        public static string Label_NotSet {
            get {
                return ResourceManager.GetString("Label_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Consumables.
        /// </summary>
        public static string Label_OtherConsumable {
            get {
                return ResourceManager.GetString("Label_OtherConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pabd.
        /// </summary>
        public static string Label_Pabd {
            get {
                return ResourceManager.GetString("Label_Pabd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pabd Catheter.
        /// </summary>
        public static string Label_PabdCatheter {
            get {
                return ResourceManager.GetString("Label_PabdCatheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Electrodes.
        /// </summary>
        public static string Label_PatchElectrodes {
            get {
                return ResourceManager.GetString("Label_PatchElectrodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pclos.
        /// </summary>
        public static string Label_Pclos {
            get {
                return ResourceManager.GetString("Label_Pclos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdet.
        /// </summary>
        public static string Label_Pdet {
            get {
                return ResourceManager.GetString("Label_Pdet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Label_Pressure {
            get {
                return ResourceManager.GetString("Label_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Date.
        /// </summary>
        public static string Label_Production_Date {
            get {
                return ResourceManager.GetString("Label_Production_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pura.
        /// </summary>
        public static string Label_Pura {
            get {
                return ResourceManager.GetString("Label_Pura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pura Catheter.
        /// </summary>
        public static string Label_PuraCatheter {
            get {
                return ResourceManager.GetString("Label_PuraCatheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pves.
        /// </summary>
        public static string Label_Pves {
            get {
                return ResourceManager.GetString("Label_Pves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pves Catheter.
        /// </summary>
        public static string Label_PvesCatheter {
            get {
                return ResourceManager.GetString("Label_PvesCatheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified.
        /// </summary>
        public static string Label_Qualified {
            get {
                return ResourceManager.GetString("Label_Qualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Consumables:.
        /// </summary>
        public static string Label_RequiredConsumables {
            get {
                return ResourceManager.GetString("Label_RequiredConsumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned.
        /// </summary>
        public static string Label_Scanned {
            get {
                return ResourceManager.GetString("Label_Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string Label_Secondary {
            get {
                return ResourceManager.GetString("Label_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string Label_Serial {
            get {
                return ResourceManager.GetString("Label_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stim Probe.
        /// </summary>
        public static string Label_StimProbe {
            get {
                return ResourceManager.GetString("Label_StimProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stimulation.
        /// </summary>
        public static string Label_Stimulation {
            get {
                return ResourceManager.GetString("Label_Stimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Label_Unknown {
            get {
                return ResourceManager.GetString("Label_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinf Catheter.
        /// </summary>
        public static string Label_VinfCatheter {
            get {
                return ResourceManager.GetString("Label_VinfCatheter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinf Tubing.
        /// </summary>
        public static string Label_VinfTubing {
            get {
                return ResourceManager.GetString("Label_VinfTubing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Label_Volume {
            get {
                return ResourceManager.GetString("Label_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Consumable Compatibility file is missing. Please call Service. The software will now close..
        /// </summary>
        public static string Missing_ConsumableJSON_File {
            get {
                return ResourceManager.GetString("Missing_ConsumableJSON_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All required consumables have been registered..
        /// </summary>
        public static string Tooltip_ConsumablesRegistered {
            get {
                return ResourceManager.GetString("Tooltip_ConsumablesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Consumables as no Bypasses remaining..
        /// </summary>
        public static string Tooltip_NoMoreBypass {
            get {
                return ResourceManager.GetString("Tooltip_NoMoreBypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Consumable.
        /// </summary>
        public static string Tooltip_RemoveConsumable {
            get {
                return ResourceManager.GetString("Tooltip_RemoveConsumable", resourceCulture);
            }
        }
    }
}
